
services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    runtime: nvidia  # Использование GPU runtime
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Указываем все доступные GPU

  max-ocr:
    image: codait/max-ocr
    container_name: max-ocr-container
    ports:
      - 5000:5000
    runtime: nvidia  # Использование GPU runtime
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Указываем все доступные GPU

volumes:
  ollama:
